/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUsersIndexRouteImport } from './routes/_layout/users/index'
import { Route as LayoutRolesIndexRouteImport } from './routes/_layout/roles/index'
import { Route as LayoutReportsIndexRouteImport } from './routes/_layout/reports/index'
import { Route as LayoutOrdersIndexRouteImport } from './routes/_layout/orders/index'
import { Route as LayoutMastersIndexRouteImport } from './routes/_layout/masters/index'
import { Route as LayoutLeadsIndexRouteImport } from './routes/_layout/leads/index'
import { Route as LayoutFirmsIndexRouteImport } from './routes/_layout/firms/index'
import { Route as LayoutCustomersIndexRouteImport } from './routes/_layout/customers/index'
import { Route as LayoutUsersNewRouteImport } from './routes/_layout/users/new'
import { Route as LayoutOrdersNewRouteImport } from './routes/_layout/orders/new'
import { Route as LayoutLeadsNewRouteImport } from './routes/_layout/leads/new'
import { Route as LayoutFirmsNewRouteImport } from './routes/_layout/firms/new'
import { Route as LayoutOrdersOrderIdIndexRouteImport } from './routes/_layout/orders/$orderId/index'
import { Route as LayoutLeadsLeadIdIndexRouteImport } from './routes/_layout/leads/$leadId/index'
import { Route as LayoutCustomersCustomerIdIndexRouteImport } from './routes/_layout/customers/$customerId/index'
import { Route as LayoutLeadsLeadIdFollowupRouteImport } from './routes/_layout/leads/$leadId/followup'
import { Route as LayoutFirmsFirmIdEditRouteImport } from './routes/_layout/firms/$firmId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersIndexRoute = LayoutUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRolesIndexRoute = LayoutRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportsIndexRoute = LayoutReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersIndexRoute = LayoutOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMastersIndexRoute = LayoutMastersIndexRouteImport.update({
  id: '/masters/',
  path: '/masters/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLeadsIndexRoute = LayoutLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFirmsIndexRoute = LayoutFirmsIndexRouteImport.update({
  id: '/firms/',
  path: '/firms/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCustomersIndexRoute = LayoutCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersNewRoute = LayoutUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersNewRoute = LayoutOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLeadsNewRoute = LayoutLeadsNewRouteImport.update({
  id: '/leads/new',
  path: '/leads/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFirmsNewRoute = LayoutFirmsNewRouteImport.update({
  id: '/firms/new',
  path: '/firms/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersOrderIdIndexRoute =
  LayoutOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLeadsLeadIdIndexRoute = LayoutLeadsLeadIdIndexRouteImport.update({
  id: '/leads/$leadId/',
  path: '/leads/$leadId/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCustomersCustomerIdIndexRoute =
  LayoutCustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLeadsLeadIdFollowupRoute =
  LayoutLeadsLeadIdFollowupRouteImport.update({
    id: '/leads/$leadId/followup',
    path: '/leads/$leadId/followup',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFirmsFirmIdEditRoute = LayoutFirmsFirmIdEditRouteImport.update({
  id: '/firms/$firmId/edit',
  path: '/firms/$firmId/edit',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/firms/new': typeof LayoutFirmsNewRoute
  '/leads/new': typeof LayoutLeadsNewRoute
  '/orders/new': typeof LayoutOrdersNewRoute
  '/users/new': typeof LayoutUsersNewRoute
  '/customers/': typeof LayoutCustomersIndexRoute
  '/firms/': typeof LayoutFirmsIndexRoute
  '/leads/': typeof LayoutLeadsIndexRoute
  '/masters/': typeof LayoutMastersIndexRoute
  '/orders/': typeof LayoutOrdersIndexRoute
  '/reports/': typeof LayoutReportsIndexRoute
  '/roles/': typeof LayoutRolesIndexRoute
  '/users/': typeof LayoutUsersIndexRoute
  '/firms/$firmId/edit': typeof LayoutFirmsFirmIdEditRoute
  '/leads/$leadId/followup': typeof LayoutLeadsLeadIdFollowupRoute
  '/customers/$customerId/': typeof LayoutCustomersCustomerIdIndexRoute
  '/leads/$leadId/': typeof LayoutLeadsLeadIdIndexRoute
  '/orders/$orderId/': typeof LayoutOrdersOrderIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof LayoutIndexRoute
  '/firms/new': typeof LayoutFirmsNewRoute
  '/leads/new': typeof LayoutLeadsNewRoute
  '/orders/new': typeof LayoutOrdersNewRoute
  '/users/new': typeof LayoutUsersNewRoute
  '/customers': typeof LayoutCustomersIndexRoute
  '/firms': typeof LayoutFirmsIndexRoute
  '/leads': typeof LayoutLeadsIndexRoute
  '/masters': typeof LayoutMastersIndexRoute
  '/orders': typeof LayoutOrdersIndexRoute
  '/reports': typeof LayoutReportsIndexRoute
  '/roles': typeof LayoutRolesIndexRoute
  '/users': typeof LayoutUsersIndexRoute
  '/firms/$firmId/edit': typeof LayoutFirmsFirmIdEditRoute
  '/leads/$leadId/followup': typeof LayoutLeadsLeadIdFollowupRoute
  '/customers/$customerId': typeof LayoutCustomersCustomerIdIndexRoute
  '/leads/$leadId': typeof LayoutLeadsLeadIdIndexRoute
  '/orders/$orderId': typeof LayoutOrdersOrderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/firms/new': typeof LayoutFirmsNewRoute
  '/_layout/leads/new': typeof LayoutLeadsNewRoute
  '/_layout/orders/new': typeof LayoutOrdersNewRoute
  '/_layout/users/new': typeof LayoutUsersNewRoute
  '/_layout/customers/': typeof LayoutCustomersIndexRoute
  '/_layout/firms/': typeof LayoutFirmsIndexRoute
  '/_layout/leads/': typeof LayoutLeadsIndexRoute
  '/_layout/masters/': typeof LayoutMastersIndexRoute
  '/_layout/orders/': typeof LayoutOrdersIndexRoute
  '/_layout/reports/': typeof LayoutReportsIndexRoute
  '/_layout/roles/': typeof LayoutRolesIndexRoute
  '/_layout/users/': typeof LayoutUsersIndexRoute
  '/_layout/firms/$firmId/edit': typeof LayoutFirmsFirmIdEditRoute
  '/_layout/leads/$leadId/followup': typeof LayoutLeadsLeadIdFollowupRoute
  '/_layout/customers/$customerId/': typeof LayoutCustomersCustomerIdIndexRoute
  '/_layout/leads/$leadId/': typeof LayoutLeadsLeadIdIndexRoute
  '/_layout/orders/$orderId/': typeof LayoutOrdersOrderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/firms/new'
    | '/leads/new'
    | '/orders/new'
    | '/users/new'
    | '/customers/'
    | '/firms/'
    | '/leads/'
    | '/masters/'
    | '/orders/'
    | '/reports/'
    | '/roles/'
    | '/users/'
    | '/firms/$firmId/edit'
    | '/leads/$leadId/followup'
    | '/customers/$customerId/'
    | '/leads/$leadId/'
    | '/orders/$orderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/firms/new'
    | '/leads/new'
    | '/orders/new'
    | '/users/new'
    | '/customers'
    | '/firms'
    | '/leads'
    | '/masters'
    | '/orders'
    | '/reports'
    | '/roles'
    | '/users'
    | '/firms/$firmId/edit'
    | '/leads/$leadId/followup'
    | '/customers/$customerId'
    | '/leads/$leadId'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/'
    | '/_layout/firms/new'
    | '/_layout/leads/new'
    | '/_layout/orders/new'
    | '/_layout/users/new'
    | '/_layout/customers/'
    | '/_layout/firms/'
    | '/_layout/leads/'
    | '/_layout/masters/'
    | '/_layout/orders/'
    | '/_layout/reports/'
    | '/_layout/roles/'
    | '/_layout/users/'
    | '/_layout/firms/$firmId/edit'
    | '/_layout/leads/$leadId/followup'
    | '/_layout/customers/$customerId/'
    | '/_layout/leads/$leadId/'
    | '/_layout/orders/$orderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/': {
      id: '/_layout/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof LayoutUsersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/roles/': {
      id: '/_layout/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof LayoutRolesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reports/': {
      id: '/_layout/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof LayoutReportsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders/': {
      id: '/_layout/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof LayoutOrdersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/masters/': {
      id: '/_layout/masters/'
      path: '/masters'
      fullPath: '/masters/'
      preLoaderRoute: typeof LayoutMastersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/leads/': {
      id: '/_layout/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LayoutLeadsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/firms/': {
      id: '/_layout/firms/'
      path: '/firms'
      fullPath: '/firms/'
      preLoaderRoute: typeof LayoutFirmsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/customers/': {
      id: '/_layout/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof LayoutCustomersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/new': {
      id: '/_layout/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof LayoutUsersNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders/new': {
      id: '/_layout/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof LayoutOrdersNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/leads/new': {
      id: '/_layout/leads/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof LayoutLeadsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/firms/new': {
      id: '/_layout/firms/new'
      path: '/firms/new'
      fullPath: '/firms/new'
      preLoaderRoute: typeof LayoutFirmsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders/$orderId/': {
      id: '/_layout/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId/'
      preLoaderRoute: typeof LayoutOrdersOrderIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/leads/$leadId/': {
      id: '/_layout/leads/$leadId/'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId/'
      preLoaderRoute: typeof LayoutLeadsLeadIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/customers/$customerId/': {
      id: '/_layout/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof LayoutCustomersCustomerIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/leads/$leadId/followup': {
      id: '/_layout/leads/$leadId/followup'
      path: '/leads/$leadId/followup'
      fullPath: '/leads/$leadId/followup'
      preLoaderRoute: typeof LayoutLeadsLeadIdFollowupRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/firms/$firmId/edit': {
      id: '/_layout/firms/$firmId/edit'
      path: '/firms/$firmId/edit'
      fullPath: '/firms/$firmId/edit'
      preLoaderRoute: typeof LayoutFirmsFirmIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutFirmsNewRoute: typeof LayoutFirmsNewRoute
  LayoutLeadsNewRoute: typeof LayoutLeadsNewRoute
  LayoutOrdersNewRoute: typeof LayoutOrdersNewRoute
  LayoutUsersNewRoute: typeof LayoutUsersNewRoute
  LayoutCustomersIndexRoute: typeof LayoutCustomersIndexRoute
  LayoutFirmsIndexRoute: typeof LayoutFirmsIndexRoute
  LayoutLeadsIndexRoute: typeof LayoutLeadsIndexRoute
  LayoutMastersIndexRoute: typeof LayoutMastersIndexRoute
  LayoutOrdersIndexRoute: typeof LayoutOrdersIndexRoute
  LayoutReportsIndexRoute: typeof LayoutReportsIndexRoute
  LayoutRolesIndexRoute: typeof LayoutRolesIndexRoute
  LayoutUsersIndexRoute: typeof LayoutUsersIndexRoute
  LayoutFirmsFirmIdEditRoute: typeof LayoutFirmsFirmIdEditRoute
  LayoutLeadsLeadIdFollowupRoute: typeof LayoutLeadsLeadIdFollowupRoute
  LayoutCustomersCustomerIdIndexRoute: typeof LayoutCustomersCustomerIdIndexRoute
  LayoutLeadsLeadIdIndexRoute: typeof LayoutLeadsLeadIdIndexRoute
  LayoutOrdersOrderIdIndexRoute: typeof LayoutOrdersOrderIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutFirmsNewRoute: LayoutFirmsNewRoute,
  LayoutLeadsNewRoute: LayoutLeadsNewRoute,
  LayoutOrdersNewRoute: LayoutOrdersNewRoute,
  LayoutUsersNewRoute: LayoutUsersNewRoute,
  LayoutCustomersIndexRoute: LayoutCustomersIndexRoute,
  LayoutFirmsIndexRoute: LayoutFirmsIndexRoute,
  LayoutLeadsIndexRoute: LayoutLeadsIndexRoute,
  LayoutMastersIndexRoute: LayoutMastersIndexRoute,
  LayoutOrdersIndexRoute: LayoutOrdersIndexRoute,
  LayoutReportsIndexRoute: LayoutReportsIndexRoute,
  LayoutRolesIndexRoute: LayoutRolesIndexRoute,
  LayoutUsersIndexRoute: LayoutUsersIndexRoute,
  LayoutFirmsFirmIdEditRoute: LayoutFirmsFirmIdEditRoute,
  LayoutLeadsLeadIdFollowupRoute: LayoutLeadsLeadIdFollowupRoute,
  LayoutCustomersCustomerIdIndexRoute: LayoutCustomersCustomerIdIndexRoute,
  LayoutLeadsLeadIdIndexRoute: LayoutLeadsLeadIdIndexRoute,
  LayoutOrdersOrderIdIndexRoute: LayoutOrdersOrderIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
